source/accounts/urls.py
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView, UserChangeView, ProfileView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/change', UserChangeView.as_view(), name='change'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ImageView

router = routers.DefaultRouter()
router.register('images', ImageView)
urlpatterns = [
    path('', include(router.urls)),
    path('image/<int:pk>', ImageView.as_view({'get': 'add_image_to_favorite'}), name='fav'),
    path('image/<int:pk>', ImageView.as_view({'get': 'image_remove_favorite'}), name='fromfav'),
]

source/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('gallery.urls')),
    path("auth/", include('accounts.urls')),
    path("api/", include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/gallery/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Image(models.Model):
    image = models.ImageField(
        verbose_name='Фотография',
        default='default_image',
        null=False,
        blank=False
    )
    sign = models.CharField(
        verbose_name='Подпись',
        max_length=150,
        null=False,
        blank=False
    )
    author = models.ForeignKey(
        verbose_name='Автор',
        to=get_user_model(),
        related_name='images',
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    users = models.ManyToManyField(
        to=get_user_model(),
        related_name='favorites'
    )
    created_at = models.DateTimeField(
        verbose_name='Время создания',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='Время изменения',
        auto_now=True
    )

    def __str__(self):
        return f"{self.image} - {self.sign} - {self.author}"

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label='Имя Пользователя'
    )
    password = forms.CharField(
        required=True,
        label='Пароль',
        widget=forms.PasswordInput
    )
    next = forms.CharField(
        required=False,
        widget=forms.HiddenInput
    )


class CustomUserCreationForm(forms.ModelForm):

    password = forms.CharField(
        label='Пароль',
        strip=False,
        required=True,
        widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label='Повторите пароль',
        strip=False,
        required=True,
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = (
            'username',
            'password',
            'password_confirm',
            'first_name',
            'last_name',
            'email',
        )

        labels = {'email': 'Почта',
                  'username': 'Имя Пользователя',
                  'password_confirm': 'Повторите пароль',
                  'first_name': 'Имя',
                  'last_name': 'Фамилия',
                  }


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError('Пароль не совпадает')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))

        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email',
        )
        labels = {'email': 'Почта',
                  'first_name': 'Имя',
                  'last_name': 'Фамилия',
                  }

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, ListView

from gallery.models import Image
from .forms import LoginForm, CustomUserCreationForm, UserChangeForm


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        next = request.GET.get('next')
        form_data = {} if not next else {'next': next}
        form = self.form(form_data)
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('login')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        next = form.cleaned_data.get('next')
        user = authenticate(request, username=username, password=password)
        if not user:
            return redirect('login')
        login(request, user)
        if next:
            return redirect(next)
        return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('login')


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        context = {}
        context['form'] = form
        return self.render_to_response(context)


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'profile.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        images = Image.objects.filter(users=self.request.user)
        context['images'] = images
        return context


class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('profile', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

source/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}

<div class="d-flex justify-content-center mt-4">
    <div class="border border-4 p-5" style="width: 320px;">
        <img src="{% static 'images/logo.png' %}" alt=" " height="55" width="144">
        <div>
            <form action="" method='POST'>
                <div class='form'>
                    {% csrf_token %}
                    {{form.as_p}}
                    <input class="btn btn-secondary" type="submit" value="Войти">
                    <a class="btn btn-secondary" href="{% url 'register' %}">Регистрация</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

source/accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}
{% block content %}
    <br>
<br>
<br>
<br>
    <h1>Личная страница пользователя {{ user_obj.username }}</h1>
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Почта: {{ user_obj.email }}</p>


    <h2 class="text-center clear"> Мои избранные фотки:</h2>
    <div class="row mt-5">
    {%for image in request.user.favorites.all%}
    <div class="col-sm-6">
          <div class="row no-gutters" >
            <div class="col-md-4">
              <img src="{{image.image.url}}" class="card-img" style="width:120px;height: 120px;" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{image.sign}}</h5>
                  <p>{{image.author}}</p>
                     <p>{{image.created_at}}</p>
                    <p>{{image.updated_at}}</p>
                  <div class="container">
                      <div class="row">
                          <div class="col-sm">
                           <a href="{% url 'image_detail' image.pk %}">Детально</a>
                        </div>
                         {% if request.user.is_authenticated%}
                          {% if request.user == image.author or perms.gallery.change_image%}
                        <div class="col-sm">
                           <a href="{% url 'image_update' image.pk %}">Изменить</a>
                        </div>
                          {% endif %}
                          {% if request.user == image.author or gallery.gallery.delete_image%}
                        <div class="col-sm">
                            <form action="{% url 'image_delete' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Удалить</button>
                        </form>
                        </div>
                          {% endif %}

                           <div class="col-sm">
                                <form action="{% url 'add_favorite' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Добавить в избранное</button>
                                </form>
                        </div>
                          <div class="col-sm">
                                <form action="{% url 'add_favorite' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Удалить из избранного</button>
                                </form>
                        </div>
                          {% endif %}
                      </div>
                    </div>
              </div>
            </div>
          </div>
    </div>
    {%endfor%}

</div>




{% endblock %}

source/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <form action="{% url 'register' %}" method="POST" enctype="multipart/form-data">
        <div class="form mt-4">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content='Зарегистрироваться' %}
        </div>
    </form>

{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}Редактировать профиль{% endblock %}

{% block content %}
<div class="container">
    <h1>Редактировать профиль</h1>
    <form action="{% url 'change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_class="btn-secondary" button_type="submit" content='Edit' %}
        <br>
    </form>
</div>

{% endblock %}