source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ImageView

router = routers.DefaultRouter()
router.register('images', ImageView)
urlpatterns = [
    path('', include(router.urls)),
    path('image/<int:pk>', ImageView.as_view({'get': 'add_image_to_favorite'}), name='fav'),
    path('image/<int:pk>', ImageView.as_view({'get': 'image_remove_favorite'}), name='fromfav'),
]

source/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('gallery.urls')),
    path("auth/", include('accounts.urls')),
    path("api/", include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/gallery/urls.py
from django.urls import path

from .views import ImageCreateView, IndexView, ImageView, ImageDeleteView, ImageUpdateView, \
    ImageFavoriteView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('image/<int:pk>', ImageView.as_view(), name='image_detail'),
    path('images/add/', ImageCreateView.as_view(), name='image_add'),
    path('images/<int:pk>/delete', ImageDeleteView.as_view(), name="image_delete"),
    path('images/<int:pk>/edit', ImageUpdateView.as_view(), name="image_update"),
    path('images/delete/<int:pk>', ImageDeleteView.as_view(), name='image_delete'),
    path('images/<int:pk>/favorite', ImageFavoriteView.as_view(), name='add_favorite')
]

source/gallery/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Image(models.Model):
    image = models.ImageField(
        verbose_name='Фотография',
        default='default_image',
        null=False,
        blank=False
    )
    sign = models.CharField(
        verbose_name='Подпись',
        max_length=150,
        null=False,
        blank=False
    )
    author = models.ForeignKey(
        verbose_name='Автор',
        to=get_user_model(),
        related_name='images',
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    users = models.ManyToManyField(
        to=get_user_model(),
        related_name='favorites'
    )
    created_at = models.DateTimeField(
        verbose_name='Время создания',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='Время изменения',
        auto_now=True
    )

    def __str__(self):
        return f"{self.image} - {self.sign} - {self.author}"

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

source/gallery/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image', 'sign')

source/gallery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from gallery.forms import ImageForm
from gallery.models import Image


class IndexView(ListView):
    template_name = 'index.html'
    model = Image
    context_object_name = 'images'
    ordering = '-created_at'


class ImageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'add_image.html'
    form_class = ImageForm
    model = Image

    def get_success_url(self):
        return reverse('profile', kwargs={'pk': self.request.user.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ImageView(DetailView):
    template_name = 'image_detail.html'
    model = Image

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        image = self.object
        users = image.users.all
        context['users'] = users
        return context


class ImageUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'update_image.html'
    form_class = ImageForm
    model = Image
    context_object_name = 'image'
    permission_required = 'gallery.change_image'

    def get_success_url(self):
        return reverse('image_detail', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user


class ImageDeleteView(PermissionRequiredMixin, DeleteView):
    model = Image
    success_url = reverse_lazy('index')

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user


class ImageFavoriteView(View):
    def post(self, request, *args, **kwargs):
        image = get_object_or_404(Image, pk=kwargs.get('pk'))
        user = request.user
        if image in user.favorites.all():
            user.favorites.remove(image)
            return redirect('index')
        user.favorites.add(image)
        return redirect('index')

source/gallery/templates/add_image.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block content %}
<div class="container">
   <form action="{% url 'image_add' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content='Добавить фотографию' %}
    </form>
</div>
{% endblock %}

source/gallery/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static '/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a href="/"><img class="nav-link d-block mx-auto" src="{% static 'images/logo.png' %}" alt="" width="260"
                         height="90"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar" id="navbarsExample07">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'change' user.pk %}" class="nav-link text-white"><i class="bi bi-gear-wide"
                                                                                       style="font-size: 3rem"></i></a>
                </li>
                <li>
                <a href="{% url 'image_add' %}" class="btn btn my-2 text-white">Добавить фотографию</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'profile' user.pk %}" class="nav-link text-white"><i class="bi bi-person-fill"
                                                                                        style="font-size: 3rem"></i></a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Выход">
                    </form>
                </li>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn my-2 text-white">Вход</a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer class="py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">© from Meta</p>
    </div>
</footer>
</body>
</html>
</DOCTYPE>

source/gallery/templates/image_detail.html
{% extends 'base.html'%}
{%block content%}

<div class="row mx-auto">
    <div class="col-md-4">
        <img src="{{image.image.url}}" class="card-img" alt="">
    </div>
    <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{image.sign}}</h5>
            <p>{{image.author}}</p>
            <p class="card-text"><b>{{image.created_at}}</b></p>
            {% if image not in request.user.favorites.all %}
            <a href=" {% url 'fav' image.pk %}" class="to-fav btn btn-secondary btn-sm mt-3" id="{{image.pk}}">Добавить
                в избранное</a><br>
            {% else %}
            <a href="{% url 'fromfav' image.pk %} " class="from-fav btn btn-secondary btn-sm mt-3" id="{{image.pk}}">Удалить
                из избранного</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="container">
    {% for user in users %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Список пользователей у кого она в избранном</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><a href="{% url 'profile' user.pk %}"><p>{{ user.username }}</p></a></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

source/gallery/templates/index.html
{% extends 'base.html'%}
{% block content %}
{% if error_text is not None %}
<h1 style="color: red;">{{ error_text }}</h1>
{% endif %}
<div class="row mt-5">
    {%for image in images%}
    <div class="col-sm-6">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="{{image.image.url}}" class="card-img" style="width:120px;height: 120px;" alt="">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Подпись - {{image.sign}}</h5>
                    <p> Автор - {{image.author}}</p>
                    <p> Дата создания - {{image.created_at}}</p>
                    <p>Дата редактирования - {{image.updated_at}}</p>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <a href="{% url 'image_detail' image.pk %}">Детально</a>
                            </div>
                            {% if request.user.is_authenticated%}
                            {% if request.user == image.author or perms.gallery.change_image%}
                            <div class="col-sm">
                                <a href="{% url 'image_update' image.pk %}">Изменить</a>
                            </div>
                            {% endif %}
                            {% if request.user.username == image.author or perms.gallery.delete_image%}
                            <div class="col-sm">
                                <form action="{% url 'image_delete' image.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-secondary btn-sm mr-5">Удалить</button>
                                </form>
                            </div>
                            {% endif %}
                            {% if image not in request.user.favorites.all %}
                            <a href=" {% url 'fav' image.pk %}" class="to-fav btn btn-secondary btn-sm mt-3"
                               id="{{image.pk}}">Добавить в избранное</a><br>
                            {% else %}
                            <a href="{% url 'fromfav' image.pk %} " class="from-fav btn btn-secondary btn-sm mt-3"
                               id="{{image.pk}}">Удалить из избранного</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}

</div>

{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

<script>

    $(document).ready(function () {

        $('.to-fav').on('click', function (e) {
            e.preventDefault();
            let pk_image = e.target.id;

            url = `http://127.0.0.1:8000/api/image/${pk_image}`

            fetch(url)
                .then((response) => {

                    document.getElementById(pk_image).innerText = 'Удалить из избранного'
                    $(this).removeClass('to-fav').addClass('from-fav');
                    return response;
                })
        });

        $('.from-fav').on('click', function (e) {
            e.preventDefault();
            let pk_image = e.target.id;
            url = `http://127.0.0.1:8000/api/image/${pk_image}`

            fetch(url)
                .then((response) => {

                    document.getElementById(pk_image).innerText = 'Добавить в избранное'
                    $(this).removeClass('from-fav').addClass('to-fav')

                    return response;
                })
        })

    })

</script>

source/gallery/templates/update_image.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}Update post{% endblock %}

{% block content %}
<div class="container">
    <h1>Редактировать Фотографию</h1>
    <form action="{% url 'image_update' image.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_class="btn-secondary" button_type="submit" content='Edit' %}
        <br>
    </form>
</div>

{% endblock %}